### ISSUE TITLE
Thermostat Entity

### ISSUE THREAD

**Issue by dragon842** [xBourner/status-card#20]
Was trying the status-card, too. And I have one comment regarding the Thermostat entity. I receive a 1 or 0 via the active_state_address (Heating ON/OFF).

_active_state_address string | list (Optional)
KNX address for reading current activity. 0 is idle, 1 is active. DPT 1_

But the entity is shown in the status no matter if there is a "1" or a "0". The Thermostat card shows  "Heizbetrieb" or "Leerlauf". I now that DD is not showing a thermostat if there is a "Leerlauf".

![Image](https://github.com/user-attachments/assets/98c957b2-84d1-4431-8fba-c2d8f58c5f9d)

**Comment by xBourner** [comment]
Yeah I saw a problem in the area card. I think I just filtered on the actual state of an entity. But most climate entities use the hvac_action. I fixed this in the area card plus but it seems it's not fixed in the status card. Will check that.

**Comment by xBourner** [comment]
should be fixed in https://github.com/xBourner/status-card/releases/tag/v2.4.2 
please check

**Comment by dragon842** [comment]
The card now shows the Thermostat entities which are in "Heizbetrieb" only, perfect.

But if you "invert / umkehren" the Thermostat in the settings you should see the entities which are in "Leerlauf" mode. But you still see the same entities again.

![Image](https://github.com/user-attachments/assets/f6bb3a90-cf37-4f0e-8d50-c4dd1d428985)

**Comment by xBourner** [comment]
Youre totally right. Thought of that and instantly forgot to check it. Its fixed now with 2.4.3

**Comment by dragon842** [comment]
Perfect
